name: "Node build an deploy"
description: "Greet someone"
inputs:
  nexus-user:
    description: "npm user"
    required: true
  nexus-pass:
    description: "npm password"
    required: true
  image-name:
    description: "Name of image to deploy"
    required: true
  github-token:
    description: "Github token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        cache: "npm"
        node-version: "16.x"
    - name: encode nexus pass
      id: prep
      run: echo ::nexus-pass name=NEXUS_PASS::`echo -n ${{ inputs.nexus-pass }} | base64`
      shell: bash
    - name: create .npmrc for nexus
      run: echo registry=https://nexus.sits.no/repository/npm-all/ \
        //nexus.sits.no/repository/npm-all/:username=${NEXUS_USERNAME} \
        //nexus.sits.no/repository/npm-all/:_password=${NEXUS_PASSWORD} > .npmrc
      shell: bash
    - run: npm install
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.nexus-user }}
        NEXUS_PASSWORD: ${{ steps.prep.outputs.NEXUS_PASS }}

    - name: Run the tests and generate coverage report
      env:
        NEXUS_USERNAME: ${{ inputs.nexus-user }}
        NEXUS_PASSWORD: ${{ steps.prep.outputs.NEXUS_PASS }}
      run: npm test -- --coverage
      shell: bash

    - run: npm run build
      shell: bash
      env:
        NEXUS_USERNAME: ${{ inputs.nexus-user }}
        NEXUS_PASSWORD: ${{ steps.prep.outputs.NEXUS_PASS }}

    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.1.0

    - name: build-pack
      run: pack build ${{ inputs.image-name }} --builder paketobuildpacks/builder:full  --buildpack gcr.io/paketo-buildpacks/nginx
      shell: bash

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: "Docker push"
      run: |
        docker push ${{ inputs.image-name }}
      shell: bash
